// import './advanced-event-handling';
// import './enums-and-literals';
// import './function-overloading';
// import './generics';
// import './generics-with-keyof';
// import './mapped-types';
// import './mixins';
import './patterns';
// import './readonly';
// import './ts-advanced-examples';
// import './utility-types';
